SELECT
  CONCAT(t1.CUSTOMER_ID, "_", t1.CALENDAR_KEY) AS CD_KEY,
  t1.CUSTOMER_ID AS CUSTOMER_KEY,
  t1.CALENDAR_KEY,
  t1.READING_TIME,
  CASE
    WHEN t1.CALENDAR_KEY = t2.EVENT_KEY THEN 1
    ELSE 0 END AS BIN_PEAK,
  t2.EVENT_KEY,	 
  t3.GENERAL_SUPPLY_KWH,	 
  t4.CONTROLLED_LOAD_KWH,	 
  t5.GROSS_GENERATION_KWH, 
  t6.NET_GENERATION_KWH,	 
  t7.OTHER_KWH,
  t1.PLUG_NAME,
  t1.READING_VALUE,
  t1.RECORD_COUNT,
  t8.ACTUAL_KWH,
  t8.BASELINE_KWH,
  t8.REBATE_AMOUNT,
  t9.ASSRTD_CLIMATE_ZONE_CD,
  t9.ASSRTD_CLIMATE_ZONE_DESC,
  t9.SMART_METER_INSTALLATION_DATE,
  t9.OPERATION_START_DATE,
  t9.OPERATION_FINISH_DATE
FROM 
  (SELECT CUSTOMER_ID, CALENDAR_KEY, READING_TIME, PLUG_NAME, READING_VALUE, RECORD_COUNT FROM sgsc_cthanplug_readings) AS t1
INNER JOIN
  (SELECT CUSTOMER_ID, READING_DATETIME, CALENDAR_KEY, EVENT_KEY FROM model_event_key) AS t2
ON
  t1.CUSTOMER_ID = t2.CUSTOMER_ID AND 
  t1.CALENDAR_KEY = t2.CALENDAR_KEY
INNER JOIN
  (SELECT CUSTOMER_ID, READING_DATETIME, CALENDAR_KEY, GENERAL_SUPPLY_KWH FROM model_general_supply_kwh) AS t3
ON
  t1.CUSTOMER_ID = t3.CUSTOMER_ID AND
  t1.CALENDAR_KEY = t3.CALENDAR_KEY
INNER JOIN
  (SELECT CUSTOMER_ID, READING_DATETIME, CALENDAR_KEY, CONTROLLED_LOAD_KWH FROM model_controlled_load_kwh) AS t4
ON
  t1.CUSTOMER_ID = t4.CUSTOMER_ID AND
  t1.CALENDAR_KEY = t4.CALENDAR_KEY
INNER JOIN
  (SELECT CUSTOMER_ID, READING_DATETIME, CALENDAR_KEY, GROSS_GENERATION_KWH FROM model_gross_generation_kwh) AS t5
ON
  t1.CUSTOMER_ID = t5.CUSTOMER_ID AND
  t1.CALENDAR_KEY = t5.CALENDAR_KEY
INNER JOIN
  (SELECT CUSTOMER_ID, READING_DATETIME, CALENDAR_KEY, NET_GENERATION_KWH FROM model_net_generation_kwh) AS t6
ON
  t1.CUSTOMER_ID = t6.CUSTOMER_ID AND
  t1.CALENDAR_KEY = t6.CALENDAR_KEY
INNER JOIN 
  (SELECT CUSTOMER_ID, READING_DATETIME, CALENDAR_KEY, OTHER_KWH FROM model_other_kwh) AS t7
ON
  t1.CUSTOMER_ID = t7.CUSTOMER_ID AND
  t1.CALENDAR_KEY = t7.CALENDAR_KEY
LEFT JOIN
  (SELECT CUSTOMER_KEY, EVENT_KEY, ACTUAL_KWH, BASELINE_KWH, REBATE_AMOUNT FROM sgsc_ctpeak_event_response) AS t8
ON
  t1.CUSTOMER_ID = t8.CUSTOMER_KEY
LEFT JOIN
  (SELECT CUSTOMER_KEY, ASSRTD_CLIMATE_ZONE_CD, ASSRTD_CLIMATE_ZONE_DESC, SMART_METER_INSTALLATION_DATE, OPERATION_START_DATE, OPERATION_FINISH_DATE FROM sgsc_ct_customer_household_data_revised) AS t9
ON
  t1.CUSTOMER_ID = t9.CUSTOMER_KEY
ORDER BY CD_KEY;